# Generated by Django 3.1.5 on 2021-01-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.TextField(null=True),
        ),
    ]
