# Generated by Django 3.1.5 on 2021-01-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_assignment_lesson_studentattendlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(upload_to='assignment_files/'),
        ),
    ]
